import { Router } from 'express';
import driverRoutes from './driver/index.js';
import clientRoutes from './client/index.js';
import adminRoutes from './admin/index.js';
import sharedRoutes from './shared/index.js';
import { authenticate } from '../middlewares/auth.middleware.js';
import { requireRole } from '../middlewares/role.middleware.js';
import routingRoutes from './shared/routing.routes.js';
import placesRoutes from './shared/places.routes.js';
import savedPlacesRoutes from './client/savedPlaces.routes.js';
import savedTripsRoutes from './client/savedTrips.routes.js';
import messageRoutes from './shared/message.routes.js';
import deviceRoutes from './shared/device.routes.js';
import otpRoutes from './shared/otp.routes.js';
import walletRoutes from './shared/wallet.routes.js';

const router = Router();
router.use('/driver', driverRoutes);
router.use('/client', clientRoutes);
router.use('/admin', authenticate, requireRole('ADMIN'), adminRoutes);
router.use('/shared', sharedRoutes);
router.use('/routing', authenticate, routingRoutes);
router.use('/places', authenticate, placesRoutes);
router.use(savedPlacesRoutes);
router.use(savedTripsRoutes);
router.use(messageRoutes);
router.use(deviceRoutes);
router.use(otpRoutes);
router.use(walletRoutes);

export default router;
